development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: web-nitaku_development
  host: localhost
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: web-nitaku_test
  host: localhost
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: web-nitaku_production
  host: localhost
  username: root
  password:
